version: "3.8"
services:
  react-app:
    image: react-app
    restart: always
    build: ./client/
    stdin_open: true
    ports:
      - "3000:3000"
    depends_on: api-server
  api-server:
    image: api-server
    restart: always
    build: ./server/
    ports:
      - "5000:5000"