version: "3.8"
services:
  react-app:
    image: react-app
    build: ./client/
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - whois-app
    volumes:
      - ./client/:/usr/src/app
      - /usr/src/app/node_modules
  api-server:
    image: api-server
    build: ./server/
    ports:
      - "5000:5000"
    networks:
      - whois-app
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
networks:
  whois-app:
    driver: bridge